[Feature]: support `no_std` environments
akubera/bigdecimal-rs pull request #97
Opened 2023-02-25 00:26 UTC by bigherc18

2023-02-25 10:12 UTC, tdelabro requested changes

2023-02-25 10:12 UTC, tdelabro commented on src/with_std.rs
> +use std::collections::hash_map::DefaultHasher;
It looks to me that this one is only used in tests.
So its `no_std` counterpart `siphasher` should be a `dev-dependency` and you should only export it when testing.
So either do the import directly in the `#[test]` modules or keep it here, but behind a `#[cfg(test)]` flag

2023-02-25 10:29 UTC, bigherc18 commented on src/without_std.rs
> +// use core::error::Error;
It's commented, I left a TODO comment to make sure we fix it later

2023-02-25 13:40 UTC, tdelabro requested changes

2023-02-25 13:40 UTC, tdelabro commented on src/lib.rs
> +use crate::f32::DIGITS as DIGITS_f32;
Use `f64::DIGITS` and `f32::DIGITS` in your code directly, rather than exporting it twice and aliasing it.
Same for `PI`

2023-02-25 13:40 UTC, tdelabro commented on src/lib.rs
> +        let scale = crate::cmp::max(self.scale, other.scale);
Isn't `cmp` already in the scope? Do you really need to specify `crate` again?

2023-02-25 13:40 UTC, tdelabro commented on src/with_std.rs
> +use std::collections::hash_map::DefaultHasher;
#[cfg(test)]

2023-02-25 13:40 UTC, tdelabro commented on src/without_std.rs
> +use num_traits::float::FloatCore;
Why is this import needed? Which of its methods are you using in `lib.rs`?

2023-02-25 13:55 UTC, bigherc18 commented on src/lib.rs
> +use crate::f32::DIGITS as DIGITS_f32;
```
error[E0223]: ambiguous associated type
    --> src/lib.rs:1996:13
     |
1996 |             f64::consts::PI,
     |             ^^^^^^^^^^^
     |
help: you are looking for the module in `std`, not the primitive type
     |
1996 |             std::f64::consts::PI,
     |             +++++
```

2023-02-25 14:01 UTC, bigherc18 commented on src/lib.rs
> +use crate::f32::DIGITS as DIGITS_f32;
it works using `crate::f64::consts::PI`

2023-02-26 00:21 UTC, bigherc18 commented on src/without_std.rs
> +use num_traits::float::FloatCore;
There was a comment explaining why it's needed and you asked to remove because it's unnecessary here: https://github.com/akubera/bigdecimal-rs/pull/97#discussion_r1117897038

```
// Without this we get the following error:
// error[E0599]: no method named `powi` found for type `f64` in the current scope
```

2023-02-26 14:29 UTC, tdelabro commented on src/without_std.rs
> +use num_traits::float::FloatCore;
haha sorry. Well maybe put it back then ;)

2023-02-26 14:31 UTC, tdelabro commented on src/lib.rs
> +// TODO: should we implement Error for no_std environments ?
No we won't.
Not until the core::error::Error API is stabilized

2023-02-26 14:33 UTC, tdelabro commented on src/lib.rs
> +use crate::convert::TryFrom;
Why is the `cmp` import not using `crate`? Does it work differently from the other?

2023-02-26 14:33 UTC, tdelabro approved these changes

2023-02-26 21:10 UTC, akubera commented
This changes the minimum supported rust version to 1.43, by my estimation. Though I don't really like we're straying away from num-bigint's 1.31, I don't *think* too many people will be upset by dropping versions old than 3 years. 

Let's update version in the README (last line)

2023-02-27 09:13 UTC, bigherc18 commented
@akubera 
> Let's update version in the README (last line)

I can't see any version mentioned in the README

2023-02-27 09:21 UTC, bigherc18 commented
> This changes the minimum supported rust version to 1.43

We can also avoid this easily, because it comes from using `siphasher`and it's only used during tests, we should either replace the `siphasher` with a crate that support `edition = 2015` or only run the tests that uses hash when on std

What do you think ?

2023-02-27 22:16 UTC, bigherc18 commented
@akubera would you please take a look again, we no longer need to change the minimum supported version

We're using your `bigdecimal-rs` library in our projects and we need the `no_std` support, we'd like you to merge this PR instead of maintaining our own fork

2023-04-18 23:22 UTC, eranrund commented
We would also love to see this gets merged! Any chance that might happen?

2023-04-19 09:20 UTC, tdelabro commented
@akubera What is preventing us to merge?

2023-05-10 02:46 UTC, merged

2023-05-21 16:58 UTC, akubera commented
I think we have to require `alloc` so I'm removing that optional feature.

Unless I'm missing something, num-bigint requires alloc, so we're not restricting our environments any more than our dependencies.